---
- name: "Role {{ role_name }}"
  vars:
    foo_: "{{ local_context_data[0]['foo'] | default(foo) }}"
    
  when:
    - only_role is undefined or only_role == role_name
  block:
  - import_tasks: files_and_dirs.yml

  - name: Install autoup local locking mechanism
    include_tasks: install_autoup_local_locking.yml
    when: 
      - install_autoup_local_locking

  - import_tasks: set_hostname.yml

  - include_tasks: set_time.yml
