---
- name: Reboot guest
  when: current_pve_host is defined
  include_role:
    role: pve-guest
    tasks_from: reboot

- name: Reboot the system
  reboot:
    msg: "Reboot initiated by Ansible for upgrade"
  when: current_pve_host is not defined

- name: Wait for system to come back online
  become: false
  local_action:
    module: wait_for
    host: "{{ ansible_host }}"
    port: 22
    state: started
    delay: 10
    timeout: 600 # 10 minutes
