---
- name: "Modify hostname of non-containerized systems ({{ ansible_hostname }} -> {{ inventory_hostname }})"
  shell:
    executable: /usr/bin/bash
    cmd: |
      hostnamectl set-hostname {{ inventory_hostname }}
  notify: Reboot vm
  when:
    - (not is_virtual) or custom_fields.technology == "vm"
    - ansible_hostname != inventory_hostname
