---
- name: "Modify hostname of non-containerized systems ({{ ansible_hostname }} -> {{ inventory_hostname }})"
  shell:
    executable: /bin/bash
    cmd: |
      hostnamectl set-hostname {{ inventory_hostname }}
  register: change_hostname
  when:
    - (not is_virtual) or technology == "vm"
    - ansible_hostname != inventory_hostname

- include_tasks: reboot_system.yml
  when: change_hostname.changed
