---
- name: NGINX
  when:
    - only_role is undefined or only_role == "nginx"
  block:
  - name: Install nginx
    include_tasks: install.yml
    when: 
      - not quick
    
  - name: Place snippets for optional inclusion in config
    include_tasks: place_snippets.yml

  - name: Configure nginx
    include_tasks: configure.yml
    when: 
      - nginx_config is defined or 
        ((local_context_data is defined and 
          local_context_data[0] is mapping) and
          'nginx_config' in local_context_data[0] | default([]))

  - name: Place ansible_local
    include_tasks: ansible_local.yml

  - name: Setup nginx_node_exporter
    include_tasks: setup_nginx_node_exporter.yml
    when:
      - nginx_exporter_enabled
      - not quick
