---
- name: Place Stub status file
  copy:
    src: "node_exporter.conf"
    dest: "/etc/nginx/conf.d/node_exporter.conf"
    mode: '0644'
  register: nginx_stub_status_file

- name: Reload Nginx service
  systemd:
    name: nginx
    state: restarted
  when: nginx_stub_status_file.changed


##############################

- name: EXPORTER LATEST VERSION
  block:
  - name: Get latest version from github
    shell:
      executable: "{{ ansible_python.executable }}"
      cmd: |
        import os
        import json
        import requests

        # GitHub repository and API endpoint
        api_url = "https://api.github.com/repos/{{ nginx_exporter_repo }}/releases/latest"

        # Get the latest release version using requests and json
        response = requests.get(api_url)
        data = response.json()
        print(data.get("tag_name").strip("v"))
    register: latest_version_query
    changed_when: false

  - name: Store nginx_exporter_latest_version
    set_fact:
      nginx_exporter_latest_version: "{{ latest_version_query.stdout }}"

- debug:
    var: ansible_local.nginx.prometheus_exporter_version

- name: Download and extract nginx-prometheus-exporter
  vars:
    current_version: "{{ ansible_local.nginx.prometheus_exporter_version }}"
    installation_version: "{{ nginx_exporter_latest_version if current_version == '' or upgrade else current_version }}"
  unarchive:
    src: "https://github.com/{{ nginx_exporter_repo }}/releases/download/v{{ installation_version }}/nginx-prometheus-exporter_{{ installation_version }}_linux_amd64.tar.gz"
    dest: "/usr/local/bin"
    remote_src: yes

- name: Create nginx_exporter user
  user:
    name: nginx_exporter
    system: yes

- name: Create Systemd Service File
  template:
    src: nginx_prometheus_exporter.service.j2
    dest: /etc/systemd/system/nginx_prometheus_exporter.service
    mode: 644
  register: nginx_prometheus_exporter_service_file

- name: Reload Systemd daemon
  systemd:
    daemon_reload: yes
  when: nginx_prometheus_exporter_service_file.changed

- name: Start nginx-prometheus-exporter
  service:
    name: nginx_prometheus_exporter
    state: started
    enabled: yes
