---
- name: Place Stub status file
  copy:
    src: "node_exporter.conf"
    dest: "/etc/nginx/conf.d/node_exporter.conf"
    mode: '0644'
  register: nginx_stub_status_file

- name: Reload Nginx service
  systemd:
    name: nginx
    state: restarted
  when: nginx_stub_status_file.changed


##############################


- name: Download and extract nginx-prometheus-exporter
  unarchive:
    src: "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v{{ nginx_node_exporter_version }}/nginx-prometheus-exporter_{{ nginx_node_exporter_version }}_linux_amd64.tar.gz"
    dest: "/usr/local/bin"
    remote_src: yes

- name: Create nginx_exporter user
  become: true
  user:
    name: nginx_exporter
    system: yes

- name: Create Systemd Service File
  become: true
  template:
    src: nginx_prometheus_exporter.service.j2
    dest: /etc/systemd/system/nginx_prometheus_exporter.service
    mode: 644
  register: nginx_prometheus_exporter_service_file

- name: Reload Systemd daemon
  become: true
  systemd:
    daemon_reload: yes
  when: nginx_prometheus_exporter_service_file.changed

- name: Start nginx-prometheus-exporter
  become: true
  service:
    name: nginx_prometheus_exporter
    state: started
    enabled: yes
  when: nginx_prometheus_exporter_service_file.changed
