---
semaphore_projects:
  - name: infrastructure
    #max_parallel_tasks: "5" # implemented, but optional
    keystore: # ssh only
      name: "ansible-ssh-key"
      local_path: "~/.ssh/id_rsa"
    repositories:
      - name: "ansible-infrastructure"
        url: git@github.com:MephistoaD/ansible-infrastructure.git
        revision: master
        ssh_key: "ansible-ssh-key"
    inventories:
      - name: "netbox"
        type: "file" # in fact "file" is the only supported option
        path: "{{ inventory_file }}"
    views:
      - name: "setup"
        position: 0
      - name: "upgrade"
        position: 1
      - name: "other"
        position: 3
    task_templates:
      - name: "Setup machine"
        description: "Job which creates and installs a machine"
        playbook_filename: "playbooks/generic_playbook.yml"
        inventory: "netbox"
        repository: "ansible-infrastructure"
        view: "setup"
        vars: # implemented, optional
          - name: "target"
            title: "Target (required)"
            description: "The target system or group of the playbook"
            type: "string"
            required: false
        environment:
          deploy_guest: true

      - name: "Machine maintenance"
        description: "Job which upgrades and reboots a machine"
        playbook_filename: "playbooks/generic_playbook.yml"
        inventory: "netbox"
        repository: "ansible-infrastructure"
        view: "upgrade"
        vars: # implemented, optional
          - name: "target"
            title: "Target (required)"
            description: "The target system or group of the playbook"
            type: "string"
            required: false
        environment:
          upgrade: true
          deploy_guest: true
          serial: true
          
      - name: "Configure DNS"
        description: "Job which updates the local dns configuration"
        playbook_filename: "playbooks/generic_playbook.yml"
        inventory: "netbox"
        repository: "ansible-infrastructure"
        view: "other"
        vars: # implemented, optional
          - name: "target"
            title: "Target (required)"
            description: "The target system or group of the playbook"
            type: "string"
            required: false
        environment:
          configure_dns_job: true

      - name: "Configure Prometheus"
        description: "Job which updates prometheus configuration"
        playbook_filename: "playbooks/generic_playbook.yml"
        inventory: "netbox"
        repository: "ansible-infrastructure"
        view: "other"
        vars: # implemented, optional
          - name: "target"
            title: "Target (required)"
            description: "The target system or group of the playbook"
            type: "string"
            required: false
        environment:
          configure_prometheus_job: true
        #schedule: "*/30 * * * *" # every 30 minutes # implemented

      - name: "Daily Updates"
        description: "Job which updates the apt cache on a daily basis"
        playbook_filename: "playbooks/periodic_package_cache_update.yml"
        inventory: "netbox"
        repository: "ansible-infrastructure"
        view: "upgrade"
        environment:
          foo: bar
        schedule: "{{ '0 0 * * *' if pool == 'infra' else '' }}" # every midnight, only on prod instance

      - name: "Balance Cluster Load"
        description: "Balance Cluster Load by migrating guests"
        playbook_filename: "playbooks/balance_cluster_load.yml"
        inventory: "netbox"
        repository: "ansible-infrastructure"
        view: "other"
        environment:
          foo: bar
        #schedule: "{{ '0 0 * * *' if pool == 'infra' else '' }}" # every midnight, only on prod instance

semaphore_webhooks:
  - name: balance-pve-sample
    script: |
      curl 'http://localhost:3000/api/project/2/tasks' \
        -X POST \
        -H 'Authorization: Bearer {{ ansible_local.semaphore.users.webhook.api_token }}' \
        --data-raw '{"template_id":22,"params":{},"message":"Triggered by webhook","environment":"{}","secret":"{}"}'
