---
semaphore_upstream_repo: ansible-semaphore/semaphore

semaphore_config_path: /etc/semaphore/config.json
semaphore_max_parralel_tasks: 10

semaphore_users:
  - name: "Test User"
    login: "testuser"
    email: "test.user@foo.bar"
    password: "#trivial"
    admin: true

semaphore_add_current_project: true
semaphore_add_local_ssh_key: false

semaphore_inventory: netbox # the path in inventory/ where the inventory is stored
semaphore_project: infrastructure # the project name shown in the semaphore gui

semaphore_repository_git_url: git@github.com:MephistoaD/ansible-infrastructure.git #git@github.com:youruser/yourrepo.git
semaphore_repository_git_branch: master
semaphore_repository_name: "{{ semaphore_project }}-{{ semaphore_repository_git_branch }}"

semaphore_tasks:
  - view: config
    name: "CONFIG: generic-playbook"
    description: "ansible role without updates"
    playbook: playbooks/generic-playbook.yml
    arguments: '["-e","target=_debian"]'
    environment: '{ "deploy_guest": true }'
  - view: upgrade
    name: "UPGRADE: generic-playbook"
    description: " ansible role with updates"
    playbook: playbooks/generic-playbook.yml
    arguments: '["-e","target=_debian"]'
    environment: '{ "upgrade": true, "deploy_guest": true }'

# views sind z.T. bei der Erstellung von Task templates hardcoded in Verwendung
semaphore_views:
  - name: "config"
  - name: "upgrade"
  - name: "other"
