all:
  children:
    _pve:
      hosts:
        pve:
          ansible_host: 192.168.1.100

          # Vars needed in playbooks/add_phisical_to_netbox.yml
          site: "de-home"
          device_role: pve

          # vars needed in the playbooks/generic_playbook.yml
          device_roles:
           - "_pve"
