---
role_name: vaultwarden

prometheus_roles:
  - nginx

vaultwarden_nginx_hostname: "_"

# including vars from netbox
vaultwarden_nginx_hostname_: "{{ local_context_data[0]['vaultwarden_nginx_hostname'] | default(vaultwarden_nginx_hostname) }}"