---
groups:
- name: MaintenanceTriggers
  rules:
  - alert: PendingAptUpgradeTrigger
    expr: |
      (upgradable_package > 0)
    annotations:
      title: "Pending upgrade"
      count: "{{ $value }}"
    labels:
      autoup: MaintenanceTrigger

  - alert: PendingFlakeUpgradeTrigger
    expr: |
      (nixos_pending_flake_upgrade > 0)
    annotations:
      title: "Pending flake upgrade"
      count: "{{ $value }}"
    labels:
      autoup: MaintenanceTrigger

  - alert: PendingNextcloudUpgradeTrigger
    expr: |
      (node_exporter_nextcloud_upgrade_pending > 0)
    annotations:
      title: "A new nextcloud upgrade is available"
      count: "{{ $value }}"
    labels:
      autoup: MaintenanceTrigger

- name: RebootTriggers
  rules:
  - alert: PendingRebootTrigger
    expr: |
      (node_reboot_required > 0)
    annotations:
      title: "The instance requires a reboot"
      count: "{{ $value }}"
    labels:
      autoup: RebootTrigger

- name: Inhibitors
  rules:
  - alert: UpgradedRecentlyInhibitor
    expr: |
      (48 - ((time() - last_system_upgrade) / 60 / 60) > 0)
    annotations:
      title: "System was upgraded recently"
      count: "{{ printf \"%.4f\" $value }}"
    labels:
      autoup: Inhibitor
      origin: "System was upgraded within the last 48h"

  - alert: OpenUserSessionsInhibitor
    expr: |
      (node_exporter_open_user_shells > 0)
    annotations:
      title: "User is logged in on the system"
      count: "{{ $value }}"
    labels:
      autoup: Inhibitor

  - alert: AutoUpLockedInhibitor
    expr: |
      (node_exporter_autoup_locked > 0)
    annotations:
      title: "AutoUp is manually locked on that system"
      count: "{{ $value }}"
    labels:
      autoup: Inhibitor

  - alert: CephHealingInhibitor
    expr: |
      (ceph_pg_recovering + ceph_pg_recovery_wait + ceph_pg_degraded > 0)
    annotations:
      title: "Ceph is actively healing placement groups"
      count: "{{ $value }}"
    labels:
      autoup: Inhibitor

  - alert: CephUnhealtyInhibitor
    expr: |
      (ceph_health_status > 0)
    annotations:
      title: "Ceph is currently unhealthy"
      count: "{{ $value }}"
    labels:
      autoup: Inhibitor

  - alert: OpenvpnOpenUserConnectionsInhibitor
    expr: |
      (openvpn_active_client_connection > 0)
    annotations:
      title: "System was upgraded recently"
      count: "{{ $value }}"
    labels:
      autoup: Inhibitor

  - alert: PVECephClusterUnhealthyInhibitor
    expr: |
      (pve_ceph_health_status != 1)
    annotations:
      title: "Ceph cluster is unhealthy"
      count: "1" # is not shown in autoup since it resolves to 0
    labels:
      autoup: Inhibitor

  - alert: PVECephClusterHealthAlertInhibitor
    expr: |
      (pve_ceph_health_checks > 0)
    annotations:
      title: "Ceph cluster is unhealthy"
      count: "{{ $value }}"
    labels:
      autoup: Inhibitor

  - alert: PVEMinimumQuorumNodesReachedInhibitor
    expr: |
        round((pve_quorum_expected_votes + 1) / 2) 
        >= on(instance)
          sum by(instance) (
            pve_quorum_votes
          )
    annotations:
      title: "The minimum number of nodes for maintaining quorum is reached. Consider setting 'pvecm expected <nr>' lower if you think this is a mistake."
      count: "{{ $value }}"
    labels:
      autoup: Inhibitor

- name: Obstacles
  rules:
  - alert: LXCRunningOnPVENodeObstacle
    expr: |
      pve_guest_infopve_guest_info{type="lxc", template="0"}
