---
- name: Add custom scripts
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 744
  loop_control:
    label: "{{ item.dest }}"
  loop:
    - src: usr_local_bin_node-state.py
      dest: /usr/local/bin/node-state

- name: Add node_state to config if not set
  shell:
    cmd: |
      /usr/local/bin/node-state init
  register: init_node_state
  failed_when: init_node_state.rc == 1
  changed_when: init_node_state.rc == 0

- name: Set ansible_local file
  template:
    src: etc_ansible_facts.d_pve.fact.j2  # Path to Python script template
    dest: /etc/ansible/facts.d/pve.fact
    mode: '700'  # Set the executable permission on the script

- name: "Collect ansible_local"
  setup:
    filter: ansible_local