---
- name: PREPARE MIGRATIONS
  vars:
  
    orig_node: "{{ 
        (ansible_local.pve.guests_by_node 
        | dict2items 
        | selectattr('value.node_state', 'equalto', 'ACTIVE') 
        | map(attribute='value') 
        | sort(attribute='eligibility') | last).node
      }}"

    guests_to_move: "{{ 
        ansible_local.pve.guests_by_node[orig_node].guests 
        | selectattr('status', 'equalto', 'running')
        | sort(attribute='id', reverse=true)
      }}" # | first
    index: 0
    num_guests_to_move: 1

    migrate_once: true
  block:

  - debug:
      var: orig_node


  - set_fact:
      num_guests_to_move: "{{ guests_to_move | length }}"

  - name: Move guest away (ignoring templates)
    include_tasks: drain_node_move_guest.yml
    when:
      - not (hostvars[guest_to_move.name].pinned_on_node.name is defined and hostvars[guest_to_move.name].pinned_on_node.name == orig_node)
    loop_control:
      label: "{{ guest_to_move.id }}"
      loop_var: guest_to_move
      index_var: index
    loop: "{{ guests_to_move }}"
