---
- debug:
    msg: "configure {{ role_name }}"

- name: NETWORK CONFIG
  block:
  - name: Create network config
    ansible.builtin.template:
      src: etc_network_interfaces.j2
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: '0644'
      force: false # does not overwrite the file. -> the upstream phisical network adapter should be fetched from netbox, but can't
    register: create_network_config

  - name: Cleanup pending changes on network config
    file:
      path: /etc/network/interfaces.new
      state: absent
    when: create_network_config.changed

- name: MODIFY WEBUI
  block:
  - name: Disable nag box
    shell:
      executable: /bin/bash
      cmd: |
        grep -n -B 1 'No valid sub' /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js | grep -s void
        changed=$?
        if [ $changed == 1 ]; then 
          sed -Ezi.bak "s/(Ext.Msg.show\(\{\s+title: gettext\('No valid sub)/void\(\{ \/\/\1/g" /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
        fi
        exit $changed
    register: out
    changed_when: "out.rc == 1"
    failed_when: false

- name: POOL CREATION
  vars:
    existing_pools: "{{ ansible_local.pve.pools | selectattr('pool', 'defined') | map(attribute='pool') | map('lower') | list }}"
  block:
  - name: Create pools
    shell:
      executable: /usr/bin/bash
      cmd: |
        pvesh create /pools --poolid {{ item }}
    when:
      - (existing_pools is not defined or item not in existing_pools)
    loop: "{{ pools }}"

  - name: Delete pools if unused
    shell:
      executable: /usr/bin/bash
      cmd: |
        pvesh delete /pools/{{ item }}
    register: delete_pools
    failed_when: delete_pools.rc not in [ 0, 255 ]
    when:
      - item not in pools
    loop: "{{ ansible_local.pve.pools | selectattr('pool', 'defined') | map(attribute='pool') | map('lower') | list }}"
