---
- name: MIGRATE GUEST WHILE REBOOT
  when: dest_nodes.move_guest
  include_role: 
    name: pve-guest
    tasks_from: migrate.yml

- name: "Gather facts again to see the current status"
  setup:
    filter: ansible_local
