---
- name: SCAN VOLUMES
  block:
  - name: Scan volumes
    shell:
      executable: /bin/bash
      cmd: |
        /usr/sbin/qm disk rescan
        /usr/sbin/pct rescan
    register: disk_rescan_raw

  - debug:
      var: disk_rescan_raw.stdout_lines + disk_rescan_raw.stderr_lines

- name: PREPARE MIGRATIONS
  vars:
    orig_node: "{{ inventory_hostname }}"
    guests_to_move: "{{ ansible_local.pve.guests_by_node[orig_node].guests | rejectattr('template', 'equalto', '1') | sort(attribute='id', reverse=true) }}"
  block:
  - name: Ensure node_state = DRAIN
    shell:
      cmd: |
        /usr/local/bin/node-state drain

  - set_fact:
      num_guests_to_move: "{{ guests_to_move | length }}"
      
  - name: Move guest away (ignoring templates)
    include_tasks: drain_node_move_guest.yml
    when:
      - not (hostvars[guest_to_move.name].pinned_on_node.name is defined and hostvars[guest_to_move.name].pinned_on_node.name == orig_node)
    loop_control:
      label: "{{ guest_to_move.id }}"
      loop_var: guest_to_move
      index_var: index
    loop: "{{ guests_to_move }}"