---
- name: MIGRATE GUEST WHILE REBOOT
  vars:
    current_pve_host: "{{ inventory_hostname }}"
    technology: "{{ hostvars[guest_to_move.name].technology }}"

  include_role: 
    name: pve-guest
    tasks_from: migrate.yml

- name: "Gather facts again to see the current status"
  setup:
    filter: ansible_local
