---
- name: "Role {{ role_name }}"
  vars:
    foo_: "{{ local_context_data[0]['foo'] | default(foo) }}"
    
  when:
    - only_role is undefined or only_role == role_name
  block:
  # Assertions
  - name: "Preventive assertions of role {{ role_name }}"
    assert:
      that:
        - "{{ item.check }}"
      fail_msg: "{{ item.msg }}"
    loop_control:
      label: "{{ item.msg }}"
    loop:
      - { check: "{{ not is_virtual or custom_fields.technology == 'vm' }}", msg: "Assert that the PVE host is either a phisical device or a vm." }

  # Scripts

  # Tasks
  - include_tasks: prepare.yml
    when:
      - not quick

  - include_tasks: install.yml
    when:
      - not quick

  - include_tasks: ansible_local.yml

  - include_tasks: drain_node.yml
    when: 
      - (drain_node or upgrade)

  - include_tasks: upgrade.yml
    when: 
      - upgrade

  - include_tasks: configure.yml

  - include_tasks: join_cluster.yml
    when:
      - cluster is defined
      - not is_virtual

  - include_tasks: prometheus_exporter.yml

  - include_tasks: undrain_node.yml
    when:
      - (undrain_node or upgrade)

  # Tests
