---
postgres_users:
  - name: "semaphore_db_user"
postgres_databases:
  - name: "semaphore_db"
    owner: "semaphore_db_user"


nginx_config:
  - name: "_"
    https: false # false, self-signed, acme
    proxy_targets:
      - "localhost:3000"