---
- name: Install prometheus-node-exporter
  apt:
    pkg: "{{ item }}"
    state: present
  loop:
    - prometheus-node-exporter

- name: Ensure the prometheus-node-exporter service is started and enabled
  systemd:
    name: prometheus-node-exporter
    state: started
    enabled: yes

- name: Install custom exporter plugins
  include: install_prometheus_exporter_plugin.yml
  loop_control:
    loop_var: plugin
  loop:
    - uptime
    - session
    - upgrade
