---
- name: Install prometheus-node-exporter
  apt:
    pkg: "{{ item }}"
    state: present
  loop:
    - prometheus-node-exporter

- name: Ensure the prometheus-node-exporter service is started and enabled
  systemd:
    name: prometheus-node-exporter
    state: started
    enabled: yes

- name: CUSTOM EXPORTERS
  block:
  - name: UPTIME EXPORTER
    block:
    - name: Place uptime exporter binaries
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      register: uptime_exporter
      loop_control:
        label: "{{ item.dest }}"
      loop:
        - src: usr_local_bin_prometheus-node-exporter-uptime-plugin.py
          dest: /usr/local/bin/prometheus-node-exporter-uptime-plugin.py
        - src: etc_systemd_system_prometheus-node-exporter-uptime-plugin.service
          dest: /etc/systemd/system/prometheus-node-exporter-uptime-plugin.service
        - src: etc_systemd_system_prometheus-node-exporter-uptime-plugin.timer
          dest: /etc/systemd/system/prometheus-node-exporter-uptime-plugin.timer

    - name: Start and enable uptime exporter
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      when: uptime_exporter.changed
      loop:
        - prometheus-node-exporter-uptime-plugin.timer
        - prometheus-node-exporter-uptime-plugin.service
  
  - name: SESSIONS EXPORTER
    block:
    - name: Place sessions exporter binaries
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      register: sessions_exporter
      loop_control:
        label: "{{ item.dest }}"
      loop:
        - src: usr_local_bin_prometheus-node-exporter-sessions-plugin.sh
          dest: /usr/local/bin/prometheus-node-exporter-sessions-plugin.sh
        - src: etc_systemd_system_prometheus-node-exporter-sessions-plugin.service
          dest: /etc/systemd/system/prometheus-node-exporter-sessions-plugin.service
        - src: etc_systemd_system_prometheus-node-exporter-sessions-plugin.timer
          dest: /etc/systemd/system/prometheus-node-exporter-sessions-plugin.timer

    - name: Start and enable sessions exporter
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      when: sessions_exporter.changed
      loop:
        - prometheus-node-exporter-sessions-plugin.timer
        - prometheus-node-exporter-sessions-plugin.service
