---
- name: DEB debian update repos
  when:
    - only_role is undefined or only_role == "debian"
  block:
  - include_tasks: update.yml

  # INCLUDES
  - name: Run upgrades
    include_tasks: upgrade.yml
    when:
      - upgrade

  - name: DEB debian packages
    include_tasks: packages.yml
    when:
      - not quick

  - name: Files and directories
    include_tasks: files_and_dirs.yml

  - name: Set time
    include_tasks: set_time.yml

  - name: Install prometheus_node_exporter
    include_tasks: install_prometheus_node_exporter.yml
    when:
      - install_prometheus_node_exporter

  - name: Install autoup local locking mechanism
    include_tasks: install_autoup_local_locking.yml
    when: 
      - install_autoup_local_locking