---
- name: Install packages needed by ansible
  apt:
    pkg:
      - "{{ item }}"
    state: present
  loop:
    - gpg # import of debian repos
    - sudo # for become_user to get root
#    - debian-goodies # ansible find out if restart is needed (playbooks)

- name: Install debian_global_packages
  apt:
    pkg: "{{ item }}"
    state: present
  loop: "{{ debian_global_packages }}"

- name: Uninstall debian_global_absent_packages
  apt:
    pkg: "{{ item }}"
    state: absent
  loop: "{{ debian_global_absent_packages }}"

- name: install guest agent
  apt:
    pkg:
      - qemu-guest-agent
    state: present
  when: 
    - is_virtual
    - custom_fields.technology == 'vm'
  notify:
    - Reboot vm

