---
- name: Reconfigure packages (particularly necessary after install of a fresh vm)
  shell:
    executable: /bin/bash
    cmd: dpkg --configure -a
  register: dpkg_reconfigure
  changed_when: dpkg_reconfigure.stdout != ""

- name: Dry run apt full-upgrade
  shell: |
    apt-get -s \
      -o Debug::NoLocking=true \
      -o APT::Get::Always-Include-Phased-Updates=true \
      dist-upgrade \
      --auto-remove
  register: upgrade_output
  changed_when: false
  failed_when: false

- name: Print packages to be upgraded
  debug:
    msg: "{{ upgrade_output.stdout_lines }}"

- name: Dist-upgrade
  apt:
    clean: true # clean cache afterwards
    upgrade: dist
    autoremove: yes
    allow_change_held_packages: true # in ubuntu the package is held in case the dependency tree changed structurally
  diff: true

- include_role: 
    name: baseline
    tasks_from: "{{ tasks_from }}"
  loop_control:
    loop_var: tasks_from
  loop:
  - reboot_system
  - export_last_system_upgrade

- name: Autoremove packages
  apt:
    autoremove: yes
