---
- name: BACKUP GUEST
  block:
  - name: Create backup
    delegate_to: "{{ delegate_to_guest_pve_instance }}"
    ansible.builtin.shell: 
      executable: /bin/bash
      cmd: |
        /usr/bin/pvesh create /nodes/{{ delegate_to_guest_pve_instance }}/vzdump \
          --storage backups-{{ pool }} \
          --vmid {{ vmid }} \
          --mode snapshot \
          --notes-template "{{ backup_note }}"
    register: backup_raw

  - debug:
      var: backup_raw.stdout_lines
    
  - name: Finish play if deploy_guest == "backup"
    meta: end_host
    when:
    - deploy_guest == "backup"
