---
- name: "Install prometheus exporter"
  apt:
    pkg: "{{ item }}"
    state: present
  loop:
    - prometheus-nextcloud-exporter

- name: Create nc_exporter user
  become: true
  user:
    name: nc_exporter
    system: yes

- name: Create config directory for prometheus-nextcloud-exporter
  file:
    path: /etc/prometheus-nextcloud-exporter
    state: directory

- name: Create /etc/prometheus-nextcloud-exporter/config.yaml
  template:
    src: etc_prometheus-nextcloud-exporter_config.yaml.j2
    dest: /etc/prometheus-nextcloud-exporter/config.yaml
    owner: nc_exporter
    group: nc_exporter
    mode: 400

- name: Create Systemd Service File
  become: true
  template:
    src: etc_systemd_system_prometheus-nextcloud-exporter.service.j2
    dest: /etc/systemd/system/prometheus-nextcloud-exporter.service
    mode: 644
  register: nextcloud_prometheus_exporter_service_file

- name: Reload Systemd daemon
  become: true
  systemd:
    daemon_reload: yes
  when: nextcloud_prometheus_exporter_service_file.changed

- name: Start nginx-prometheus-exporter
  become: true
  service:
    name: prometheus-nextcloud-exporter
    state: started
    enabled: yes
  when: nextcloud_prometheus_exporter_service_file.changed

- name: CUSTOM_EXPORTERS
  block:
  - name: NEXTCLOUD EXPORTER
    block:
    - name: Place nextcloud exporter binaries
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: 755
      register: nextcloud_exporter
      loop_control:
        label: "{{ item.dest }}"
      loop:
        - src: usr_local_bin_prometheus-node-exporter-nextcloud-plugin.sh
          dest: /usr/local/bin/prometheus-node-exporter-nextcloud-plugin.sh
        - src: etc_systemd_system_prometheus-node-exporter-nextcloud-plugin.service
          dest: /etc/systemd/system/prometheus-node-exporter-nextcloud-plugin.service
        - src: etc_systemd_system_prometheus-node-exporter-nextcloud-plugin.timer
          dest: /etc/systemd/system/prometheus-node-exporter-nextcloud-plugin.timer

    - name: Start and enable nextcloud exporter
      systemd:
        daemon_reload: true
        name: "{{ item }}"
        state: restarted
        enabled: yes
      when: nextcloud_exporter.changed
      loop:
        - prometheus-node-exporter-nextcloud-plugin.timer
        - prometheus-node-exporter-nextcloud-plugin.service
