---
- name: SEMAPHORE block
  vars:
    semaphore_users_: "{{ local_context_data[0].semaphore_users if local_context_data[0] is defined else semaphore_users }}"
  block:
  - include_tasks: latest_version.yml
  - include_tasks: install.yml
  - include_tasks: users.yml
  - include_tasks: ansible_local.yml

  - include_tasks: configure_project.yml
    vars:
      admin_user: "{{ ansible_local.semaphore.users | dict2items | map(attribute='value') | selectattr('Admin', 'equalto', 'true') | first }}"
    when: semaphore_add_current_project
