---
- name: "Role: pbs"
  vars:
    pbs_discord_dark_: "{{ local_context_data[0].pbs_discord_dark | default(pbs_discord_dark) }}"
  when:
  - (only_role is not defined or only_role == "pbs")
  block:
  - incude_tasks: install.yml
    when:
      - not quick

  - incude_tasks: nag_box.yml

  - incude_tasks: dark_theme.yml