---
- name: Disable nag box
  shell:
    executable: /bin/bash
    cmd: |
      grep -n -B 1 'No valid sub' /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js | grep -s void
      changed=$?
      if [ $changed == 1 ]; then 
        sed -Ezi.bak "s/(Ext.Msg.show\(\{\s+title: gettext\('No valid sub)/void\(\{ \/\/\1/g" /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
      fi
      exit $changed
  register: out
  changed_when: "out.rc == 1"
  failed_when: false
