---
- name: "Role: alertmanager"
  vars:
    foo_: "{{ local_context_data[0].foo | default(foo) }}"
  when:
    - (only_role is not defined or only_role == "alertmanager")
  block:
  - include_tasks: install.yml
    when:
      - not quick
  - include_tasks: configure.yml
