---
- name: "Role: alertmanager"
  vars:
    alertmanager_autoup_instances_: "{{ local_context_data[0].alertmanager_autoup_instances | default(alertmanager_autoup_instances) }}"
  when:
    - (only_role is not defined or only_role == "alertmanager")
  block:
  - include_tasks: install.yml
    when:
      - not quick
  - include_tasks: configure.yml
