---
- debug:
    msg: "configure {{ role_name }}"

- name: "Pull configuration from lxc {{ vmid }}"
  delegate_to: "{{ delegate_to_guest_pve_instance }}"
  shell:
    executable: /bin/bash
    cmd: |
      # To avoid weird bugs from previous deployments, remove old config
      rm {{ nixos_tempfolder }}/{{ role_name }}.nix

      pct exec {{ vmid }} sh <<-EOT
      source /etc/set-environment
      [ -f /etc/nixos/{{ role_name }}.nix ]
      EOT
      if [ $? -eq 0 ]; then # only pulls the file if it's present
        pct pull {{ vmid }} /etc/nixos/{{ role_name }}.nix {{ nixos_tempfolder }}/{{ role_name }}.nix
      fi
  changed_when: false

- name: "Template configuration"
  delegate_to: "{{ delegate_to_guest_pve_instance }}"
  template:
    src: "role_name.nix.j2"
    dest: "{{ nixos_tempfolder }}/{{ role_name }}.nix"
  register: template_configuration

- name: "Push {{ role_name }}.nix to lxc {{ vmid }}"
  delegate_to: "{{ delegate_to_guest_pve_instance }}"
  shell:
    executable: /bin/bash
    cmd: |
      pct push {{ vmid }} {{ nixos_tempfolder }}/{{ role_name }}.nix /etc/nixos/{{ role_name }}.nix
  when: template_configuration.changed
