---
- debug:
    msg: "configure {{ role_name }}"

- name: Ensure nixos_tempfolder for config is present
  delegate_to: "{{ delegate_to_guest_pve_instance }}"
  file:
    path: "{{ nixos_tempfolder }}"
    state: directory

- name: "Pull configuration from lxc"
  delegate_to: "{{ delegate_to_guest_pve_instance }}"
  shell:
    executable: /bin/bash
    cmd: |
      # To avoid weird bugs from previous deployments, remove old config
      rm {{ nixos_tempfolder }}/{{ item }}.nix

      pct exec {{ vmid }} sh <<-EOT
      source /etc/set-environment
      [ -f /etc/nixos/{{ item }}.nix ]
      EOT
      if [ $? -eq 0 ]; then # only pulls the file if it's present
        pct pull {{ vmid }} /etc/nixos/{{ item }}.nix {{ nixos_tempfolder }}/{{ item }}.nix
      fi
  changed_when: false
  loop: "{{ nixos_config_files + current_roles }}"

- name: "Template configuration"
  delegate_to: "{{ delegate_to_guest_pve_instance }}"
  template:
    src: "{{ item }}.nix.j2"
    dest: "{{ nixos_tempfolder }}/{{ item }}.nix"
  register: template_configuration
  loop: "{{ nixos_config_files }}"

- name: "Initially deploy stub config for primary role"
  delegate_to: "{{ delegate_to_guest_pve_instance }}"
  ansible.builtin.copy:
    src: role_default.nix
    dest: "{{ nixos_tempfolder }}/{{ item }}.nix"
    force: false
  register: stub_config
  loop: "{{ current_roles }}"

- name: "Push configuration to lxc"
  delegate_to: "{{ delegate_to_guest_pve_instance }}"
  vars:
    files: "{{ nixos_config_files + current_roles if stub_config.changed else nixos_config_files }}"
  shell:
    executable: /bin/bash
    cmd: |
      pct push {{ vmid }} {{ nixos_tempfolder }}/{{ item }}.nix /etc/nixos/{{ item }}.nix
  when: template_configuration.changed or stub_config.changed
  loop: "{{ files }}"
