---

- name: Ensure needed directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/ansible/facts.d/
    - /var/lib/prometheus/node-exporter/
    - /usr/local/bin/

- name: Deploy flake_update script
  copy:
    src: usr_local_bin_export_flake_update.py
    dest: /usr/local/bin/export_flake_update
    mode: 0744

