---
- name: "Role {{ role_name }}"
  vars:
    foo_: "{{ local_context_data[0]['foo'] | default(foo) }}"
    nix_config_files:
    - "flake"
    - "configuration"

    delegate_to_pve_instance: "{{ groups['_pve'][0] }}" # the node where the lxc is created / the guest list is scraped
    delegate_to_guest_pve_instance: "{{ ansible_local.pve['guests_by_id'][vmid]['node'] }}"
  when:
    - only_role is undefined or only_role == role_name
  block:
  - name: "Collect ansible_local on {{ delegate_to_pve_instance }}"
    delegate_to: "{{ delegate_to_pve_instance }}"
    setup:
      filter: ansible_local

  # Scripts

  # Tasks
  - import_tasks: configure.yml

# -  shell: sleep 0
 #   delegate_to: "{{ delegate_to_guest_pve_instance }}"
  #  notify: "APPLY CONFIG"

  - import_tasks: apply_config.yml

  # Tests
