---
- name: "Role {{ role_name }}"
  when:
    - only_role is undefined or only_role == role_name
    - not nixos_apply_config
  block:
  # Assertions
  - name: "Preventive assertions of role {{ role_name }}"
    assert:
      that:
        - "{{ item.check }}"
      fail_msg: "{{ item.msg }}"
    loop_control:
      label: "{{ item.msg }}"
    loop:
      - { check: "{{ 'nixos' in platforms }}", msg: "The platform needs to be NixOS" }

  # Scripts
  - name: "Collect ansible_local on {{ delegate_to_pve_instance }}"
    delegate_to: "{{ delegate_to_pve_instance }}"
    setup:
      filter: ansible_local

  # Tasks
  - import_tasks: deploy_config.yml

  - import_tasks: apply_initial_config.yml
    when: stub_config.changed

  # generic preparations for other roles
  - include_tasks: provide_ssl_cert.yml
    when: nixos_provide_ssl_cert

  # Tests


- name: "Role {{ role_name }} (apply_config)"
  when:
    - nixos_apply_config
  block:
  - import_tasks: apply_config.yml