---
- name: Place configuration on nodes
  vars:
    src_ip: "{{ hostvars[inventory_hostname]['ansible_' + keepalived_interface].ipv4.address }}"
  template:
    src: etc_keepalived_keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: 0644
  register: keepalived_config_file

- name: Restart keepalived service
  systemd:
    name: keepalived
    state: restarted
    enabled: true
  when: keepalived_config_file.changed