---
groups:
- name: Records
  rules:
  - record: european_summer_time_offset
    expr: |
        (vector(1) and (month() > 3 and month() < 10))
        or
        (vector(1) and (month() == 3 and (day_of_month() - day_of_week()) >= 25) and absent((day_of_month() >= 25) and (day_of_week() == 0)))
        or
        (vector(1) and (month() == 10 and (day_of_month() - day_of_week()) < 25) and absent((day_of_month() >= 25) and (day_of_week() == 0)))
        or
        (vector(1) and ((month() == 10 and hour() < 1) or (month() == 3 and hour() > 0)) and ((day_of_month() >= 25) and (day_of_week() == 0)))
        or
        vector(0)

  - record: middle_european_time
    expr: time() + 3600 * (1 + european_summer_time_offset)

- name: Triggers
  rules:
  - alert: PendingUpgradesTrigger
    expr: |
      (apt_upgrades_pending > 0)
    annotations:
      title: "New upgrades are available from the apt repositories"
      count: "{{ $value }}"
    labels:
      autoup: trigger

  - alert: PendingRebootTrigger
    expr: |
      (node_reboot_required > 0)
    annotations:
      title: "The instance requires a reboot"
      count: "{{ $value }}"
    labels:
      autoup: trigger

- name: Inhibitors
  rules:
  - alert: StartedRecentlyInhibitor(48h)
    expr: |
      (node_exporter_system_uptime - 48 < 0)
    annotations:
      title: "System started recently"
      count: "{{ $value }}"
    labels:
      autoup: inhibitor

  - alert: OpenUserSessionsInhibitor
    expr: |
      (node_exporter_open_user_shells > 0)
    annotations:
      title: "User is logged in on the system"
      count: "{{ $value }}"
    labels:
      autoup: inhibitor

  - alert: AutoUpLockedInhibitor
    expr: |
      (node_exporter_autoup_locked > 0)
    annotations:
      title: "AutoUp is manually locked on that system"
      count: "{{ $value }}"
    labels:
      autoup: inhibitor
