---
groups:
- name: Records
  rules:
  - record: european_summer_time_offset
    expr: |
        (vector(1) and (month() > 3 and month() < 10))
        or
        (vector(1) and (month() == 3 and (day_of_month() - day_of_week()) >= 25) and absent((day_of_month() >= 25) and (day_of_week() == 0)))
        or
        (vector(1) and (month() == 10 and (day_of_month() - day_of_week()) < 25) and absent((day_of_month() >= 25) and (day_of_week() == 0)))
        or
        (vector(1) and ((month() == 10 and hour() < 1) or (month() == 3 and hour() > 0)) and ((day_of_month() >= 25) and (day_of_week() == 0)))
        or
        vector(0)

  - record: middle_european_time
    expr: time() + 3600 * (1 + european_summer_time_offset)

- name: Triggers
  rules:
  - alert: PendingAptUpgradeTrigger
    expr: |
      (upgradable_package > 0)
    annotations:
      title: "Pending upgrade"
      count: "{{ $value }}"
    labels:
      autoup: trigger

  - alert: PendingFlakeUpgradeTrigger
    expr: |
      (nixos_pending_flake_upgrade > 0)
    annotations:
      title: "Pending flake upgrade"
      count: "{{ $value }}"
    labels:
      autoup: trigger

  - alert: PendingRebootTrigger
    expr: |
      (node_reboot_required > 0)
    annotations:
      title: "The instance requires a reboot"
      count: "{{ $value }}"
    labels:
      autoup: trigger

  - alert: PendingNextcloudUpgradeTrigger
    expr: |
      (node_exporter_nextcloud_upgrade_pending > 0)
    annotations:
      title: "A new nextcloud upgrade is available"
      count: "{{ $value }}"
    labels:
      autoup: trigger

- name: Inhibitors
  rules:
  - alert: UpgradedRecentlyInhibitor
    expr: |
      (48 - ((time() - last_system_upgrade) / 60 / 60) > 0)
    annotations:
      title: "System was upgraded recently"
      count: "{{ printf \"%.4f\" $value }}h cooldown"
    labels:
      autoup: inhibitor
      origin: "System was upgraded within the last 48h"

  - alert: OpenUserSessionsInhibitor
    expr: |
      (node_exporter_open_user_shells > 0)
    annotations:
      title: "User is logged in on the system"
      count: "{{ $value }}"
    labels:
      autoup: inhibitor

  - alert: AutoUpLockedInhibitor
    expr: |
      (node_exporter_autoup_locked > 0)
    annotations:
      title: "AutoUp is manually locked on that system"
      count: "{{ $value }}"
    labels:
      autoup: inhibitor
