---
- name: "Configure prometheus data retention"
  vars:
    retention_gb_8_free: "{{ disk - 8 }}" # ~ the size of an empty debian install
    retention_gb: "{{ retention_gb_8_free | int }}"
  ansible.builtin.lineinfile:
    path: /etc/default/prometheus
    regexp: '^ARGS='
    line: 'ARGS="--storage.tsdb.retention.size={{ retention_gb }}GB"'
    state: present
    create: yes
  register: args_file

- name: Get dependency map
  become: false
  local_action: 
    module: prometheus_dependency_map_info
    inventory_dir: "{{ inventory_dir }}"
    roles_dir: "{{ playbook_dir }}/../roles"
  register: role_dependencies

- name: CONFIGURE PROMETHEUS
  vars:
    vms: "{{ groups.all | map('extract', hostvars) | selectattr('technology', 'defined') | selectattr('technology', 'ne', 'lxc') | map(attribute='inventory_hostname') | list }}"
    lxc: "{{ groups.all | map('extract', hostvars) | selectattr('technology', 'defined') | selectattr('technology', 'ne', 'vm') | map(attribute='inventory_hostname') | list }}"
    devices: "{{ groups.all | difference(groups.is_virtual) }}"
    node_exporter_hosts: "{{ devices | union(vms) }}"
    node_exporter_lxc: "{{ lxc }}"
    dependency_map: "{{ role_dependencies.dependency_map }}"
  block:
  - debug:
      var: node_exporter_hosts

  - debug:
      var: dependency_map

  - name: Configure prometheus
    vars:
      rules_templates: "{{ lookup('ansible.builtin.fileglob', 'templates/rules/*.j2') | split(',') | map('regex_replace','^.*/(.*)$','\\1') }}"
      rules_files: "{{ lookup('ansible.builtin.fileglob', 'rules/*') | split(',') | map('regex_replace','^.*/(.*)$','\\1') }}"
    block:
    - debug: var=rules_files

    - name: Place prometheus configuration
      template:
        src: "prometheus.yml.j2"
        dest: "/etc/prometheus/prometheus.yml"
        owner: root
        group: root
        mode: '0644'
      register: prometheus_config

    - name: Template prometheus rules
      template:
        src: "rules/{{ item }}"
        dest: "/etc/prometheus/{{ item[:-3] }}"
        owner: root
        group: root
        mode: '0644'
      register: prometheus_rules_templates
      loop: "{{ rules_templates }}"

    - name: Place prometheus rules
      copy:
        src: "rules/{{ item }}"
        dest: "/etc/prometheus/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      register: prometheus_rules
      loop: "{{ rules_files }}"

- name: Execute promtool script
  shell: /bin/promtool check config /etc/prometheus/prometheus.yml
  register: prometheus_config_validation
  failed_when: false
  changed_when: false

- name: Fail in case of invalid config
  fail:
    msg: "{{ prometheus_config_validation.stderr }}"
  when: prometheus_config_validation.rc != 0

- name: Reload prometheus
  systemd:
    name: prometheus
    state: reloaded
  when: >
    prometheus_config.changed or prometheus_rules_templates.changed or prometheus_rules.changed or args_file.changed
