---
- name: Get groups depending on nginx
  become: false
  vars:
    role_name: nginx
  local_action: 
    module: shell
    cmd: python3 ../roles/prometheus/get_dependency_map.py --inventory {{ inventory_file }}
  changed_when: false
  register: dependency_map_raw

- name: CONFIGURE PROMETHEUS
  vars:
    guests: "{{ groups.all | map('extract', hostvars) | selectattr('custom_fields.technology', 'defined') | selectattr('custom_fields.technology', 'ne', 'lxc') | map(attribute='inventory_hostname') | list }}"
    devices: "{{ groups.all | difference(groups.is_virtual) }}"
    node_exporter_hosts: "{{ devices | union(guests) }}"
    pve_exporter_hosts: "{{ groups._pve_node }}"
    dependency_map: "{{ dependency_map_raw.stdout | from_json }}"
  block:
  - debug:
      var: node_exporter_hosts

  - debug:
      var: pve_exporter_hosts

  - debug:
      var: dependency_map

  - name: Place prometheus configuration (changes always reordering the hosts list)
    template:
      src: "prometheus.yml.j2"
      dest: "/etc/prometheus/prometheus.yml"
      owner: root
      group: root
      mode: '0644'
    register: prometheus_config

- name: Execute promtool script
  shell: /bin/promtool check config /etc/prometheus/prometheus.yml
  register: prometheus_config_validation
  failed_when: false
  changed_when: false

- name: Fail in case of invalid config
  fail:
    msg: "{{ prometheus_config_validation.stderr }}"
  when: prometheus_config_validation.rc != 0

- name: Reload prometheus
  systemd:
    name: prometheus
    state: reloaded
  when: >
    prometheus_config.changed
