---
- name: "Role: prometheus"
  when:
    - (only_role is not defined or only_role == "prometheus")
  block:
  - include_tasks: install.yml
    when:
      - not quick
      - not configure_prometheus_job
      
  - include_tasks: configure.yml
