---
grafana_default_admin_user: admin

grafana_datasources:
  prometheus:
    - "{{ groups._prometheus }}"

nginx_config:
  - name: "_"
    https: self-signed # false, self-signed, acme
    proxy_to_http: true
    proxy_targets:
      - "127.0.0.1:3000"