---
grafana_default_admin_user: admin

grafana_datasources:
  prometheus:
    - "{{ groups._prometheus }}"

nginx_config:
  - name: "_"
    https: false # false, self-signed, acme
    proxy_targets:
      - "localhost:3000"