---
dependencies:
  - role: debian
    when: 
      - not configure_dns_job or configure_dns_job is undefined
  
  - role: keepalived
    when:
      - cluster_leader is defined
      - not configure_dns_job or configure_dns_job is undefined

  - role: unbound
    when: 
      - pihole_as_recursive_dns
      - not configure_dns_job or configure_dns_job is undefined