---
- debug:
    msg: pre-upgrade

- name: Restart self-healing ability
  shell:
    executable: /bin/bash
    cmd: "{{ item }}"
  register: start_healing
  loop:
    # - /usr/bin/ceph osd unset pause
    # - /usr/bin/ceph osd unset nodown
    # - /usr/bin/ceph osd unset nobackfill
    - /usr/bin/ceph osd unset norebalance
    - /usr/bin/ceph osd unset norecover
    - /usr/bin/ceph osd unset noout

- debug:
    var: item.stdout_lines + item.stderr_lines
  loop_control:
    label: "{{ item.cmd }}"
  loop: "{{ start_healing.results }}"
