---
- debug:
    msg: pre-upgrade

- name: Stop self-healing ability
  shell:
    executable: /bin/bash
    cmd: "{{ item }}"
  register: stop_healing
  loop:
    - /usr/bin/ceph osd set noout # Prevents Ceph from marking an OSD as "out" when it stops responding.
    - /usr/bin/ceph osd set norecover # Prevents the cluster from initiating data recovery.
    - /usr/bin/ceph osd set norebalance # Prevents the rebalancing of data across OSDs.
    - /usr/bin/ceph osd set nobackfill # Stops Ceph from performing backfill operations.
    - /usr/bin/ceph osd set nodown # Prevents Ceph from marking an OSD as "down" even if it stops responding.
    # - /usr/bin/ceph osd set pause # Pauses all client I/O and internal operations on OSDs. -> do not use for routine maintenance

- debug:
    var: item.stdout_lines + item.stderr_lines
  loop_control:
    label: "{{ item.cmd }}"
  loop: "{{ stop_healing.results }}"