- name: "Role {{ role_name }}"
  when:
    - only_role is undefined or only_role == role_name
  block:
  - name: Install docker
    apt:
      pkg: "{{ item }}"
      state: present
    when:
      - not quick
    loop:
      - docker.io
      - docker-compose
