---
- name: Find movable services
  debug:
    msg: "Service {{ service }} is on host {{ inventory_hostname }}"

- name: Stop service on current node
  community.docker.docker_compose:
    project_src: /root
    project_name: "{{ service }}"
    files: "{{ service }}.yml"
    state: absent
    remove_orphans: true
  register: stop_service

- name: Start service on other node
  delegate_to: "{{ groups._docker | difference([inventory_hostname]) | first }}"
  community.docker.docker_compose:
    project_src: /root
    project_name: "{{ service }}"
    files: "{{ service }}.yml"
    state: present
    remove_orphans: true
  register: start_service
