---
- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip
    - python3-virtualenv
    - git

- name: Create autoup group
  group:
    name: autoup
    state: present

- name: Create autoup system user
  user:
    name: autoup
    system: yes
    group: autoup
    home: "/opt/autoup"
    create_home: true
    shell: /bin/false

- name: Clone GitHub repository
  become_user: autoup
  git:
    repo: "{{ upstream_repo }}"
    dest: "{{ autoup_dir }}"
    clone: yes
    update: "{{ upgrade }}"
    force: "{{ upgrade }}"

- name: Place favicon
  copy:
    src: "{{ autoup_dir }}/favicon.ico"
    dest: "/var/www/html/favicon.ico"
    remote_src: true
    force: "{{ upgrade }}"

- name: Install python dependencies
  ansible.builtin.pip:
    requirements: "{{ autoup_dir }}/requirements.txt"
    virtualenv: "{{ autoup_dir }}/venv"
    