---
- name: "Role {{ role_name }}"
  vars:
    config_yml_: "{{ local_context_data[0]['config_yml'] | default(config_yml) }}"

  when:
    - only_role is undefined or only_role == role_name
  block:

  # Tasks
  - include_tasks: download.yml
    when:
      - not quick

  - include_tasks: configure.yml


  - include_tasks: start.yml
