---
- name: Add Sury PHP repository key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: Add Sury PHP repository
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present

- name: Update cache
  apt:
    update_cache: yes
  changed_when: false