---
- name: Add Sury PHP repository key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: Add Sury PHP repository
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present

- name: Update cache
  apt:
    update_cache: yes
  changed_when: false

- name: Install PHP packages
  apt:
    pkg: "{{ item }}"
    state: present
  loop:
    - php
    - php-fpm
    - "{{ php_packages | default([]) }}"

- name: "Make sure the apache2 package is not installed"
  apt:
    pkg: apache2
    state: absent

- name: "Remove traces of apache2 package"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/www/html
    - /etc/apache2
