---
- name: Install php
  include_tasks: install.yml
  when:
    - only_role is undefined or only_role == "php"

- name: Get the version of the currently running PHP installation
  shell: "php -v | head -n 1 | awk '{print $2}' | cut -d. -f1,2"
  register: php_version_raw
  changed_when: false

- name: Set fact php_version
  set_fact:
    php_version: "{{ php_version_raw.stdout }}"

- name: Tune php
  include_tasks: tune.yml
  when:
    - only_role is undefined or only_role == "php"

