---
- name: "Set ansible_local script"
  template:
    src: etc_ansible_facts.d_postgres.fact.j2  # Path to your Python script template
    dest: /etc/ansible/facts.d/postgres.fact
    mode: '0700'  # Set the executable permission on the script

- name: Gather ansible_local facts
  setup:
    filter: ansible_local