---
- name: Postgres is listening on it's default port on localhost
  block:
    - name: Confirm Postgres is listening on {{ postgres_listen_address }}:5432
      shell: netstat -ltn | grep -q -E '^tcp.*{{ postgres_listen_address }}:5432\s+.*LISTEN\s*$'
      register: postgres_listening
      changed_when: false
      failed_when: false

    - name: "TEST: If postgres is listening on it's default port on localhost"
      fail:
        msg: "Postgres is{{ ' NOT' if postgres_listening.rc != 0 else '' }} listening on {{ postgres_listen_address }}:5432"
      when: postgres_listening.rc != 0
