---
- name: Ensure PostgreSQL configuration options are set
  ansible.builtin.replace:
    path: /etc/postgresql/{{ postgres_major_version }}/main/postgresql.conf
    regexp: '^(\s*)#?\s*({{ item.key }}\s*=\s*.*)$'
    replace: '{{ item.key }} = {{ item.value }}'
    backup: no
  loop:
    - { key: 'max_connections', value: '200' }
    - { key: 'shared_buffers', value: "{{ (ansible_memory_mb['real']['total'] * 0.25) | int }}MB" } # Factor comes from https://pgtune.leopard.in.ua
    - { key: 'effective_cache_size', value: "{{ (ansible_memory_mb['real']['total'] * 0.75) | int }}MB" }
    - { key: 'maintenance_work_mem', value: "{{ (ansible_memory_mb['real']['total'] * 0.0625) | int }}MB" }
    - { key: 'checkpoint_completion_target', value: '0.9' }
#    - { key: 'wal_buffers', value: '7864kB' } # default is based on shared_buffers
    - { key: 'default_statistics_target', value: '100' }
    - { key: 'random_page_cost', value: '1.5' }
    - { key: 'effective_io_concurrency', value: '100' }
    - { key: 'work_mem', value: "{{([(ansible_memory_mb['real']['total']*1024 /16384) | int, 64]|min) }}kB" }
    - { key: 'min_wal_size', value: '1GB' }
    - { key: 'max_wal_size', value: '4GB' }
  register: postfix_config

- name: Confirm postgres config is valid
  become: true
  become_user: postgres
  shell: "/usr/lib/postgresql/{{ postgres_major_version }}/bin/postgres --config-file=/etc/postgresql/{{ postgres_major_version }}/main/postgresql.conf -C data_directory"
  register: confirm_config
  failed_when: false
  changed_when: false

- name: Fail if config is invalid
  fail:
    msg: "{{ confirm_config.stderr }}"
  when: confirm_config.rc != 0

- name: Restart PostgreSQL service
  ansible.builtin.service:
    name: postgresql
    state: restarted
  when: postfix_config.changed
