---
- hosts: "{{ device_role if '_' == device_role[0] else '_' + device_role }}"
  gather_facts: false
  tasks:
    - name: Deploy guest
      vars:
        guest_storage: "node-local"
        guest_default_user: "debian" # for vm only
        gateway: "192.168.2.1"
        nameserver: "192.168.2.250" # for vm only, lxc defaults to dns of host
        swap_default_size: 0 # for lxc only
        delegate_to_pve_instance: "{{ groups['_pve_node'][0] }}" # the node where the lxc is created / the guest list is scraped
      include_tasks: "tasks/deploy_{{ custom_fields.technology }}.yml" # deploy_lxc.yml or deploy_vm.yml
      when: 
        - is_virtual
        - custom_fields.technology is defined
        - deploy_guest is defined
        - deploy_guest

    - name: Gather Facts
      setup:

    - name: Configure hosts
      include_role:
        name: "{{ current_role | regex_replace('^_', '') }}"
      loop: "{{ include_roles | default([device_role]) }}"
      loop_control:
        loop_var: current_role
