---
- hosts: "{{ target | default('all') }}"
  gather_facts: false
  serial: "{{ serial | default(false) | bool }}"
  pre_tasks:
    # Assertions
    - name: "Preventive assertions of generic_playbook"
      vars:
        foo: bar
      assert:
        that:
          - "{{ item.check }}"
        fail_msg: "{{ item.msg }}"
      loop_control:
        label: "{{ item.msg }}"
      loop:
        - check: device_roles is defined
          msg: "Assert that the host has the device_roles field defined"

    # Prepare
    - name: Manage guest
      include_tasks: "tasks/manage_guest.yml"
      when: 
        - is_virtual
        - custom_fields.technology is defined
        - deploy_guest is defined
        - deploy_guest or deploy_guest == "only"

  tasks:
    - name: Gather Facts
      setup:
      when: '"nixos" not in platforms[0]'

    # Run
    - name: APPLY ROLES
      block:
      - name: Configure hosts
        vars:
          include_roles: "{{ [include_role] if include_role is defined }}"
          current_roles: "{{ include_roles | default(device_roles) | map('regex_replace', '^_', '') | list }}"
        include_role:
          name: "{{ current_role }}"
        loop: "{{ current_roles }}"
        loop_control:
          loop_var: current_role

      rescue:
      - debug:
          msg: here comes the rescue task

      - name: Restore guest
        include_tasks: "tasks/restore_guest.yml"
        when:
          - is_virtual
          - custom_fields.technology is defined
          - deploy_guest == "backup" or (upgrade and deploy_guest)
          - not prohibit_restore

      - fail:
          msg: "rescue operation is not appropiate"
        # only reaches this point if nothing was restored