---
- hosts: "{{ target | default('all') }}"
  gather_facts: false
  serial: "{{ serial | default(false) | bool }}"
  pre_tasks:
    # Assertions
    - name: "Preventive assertions of generic_playbook"
      assert:
        that:
          - "{{ item.check }}"
        fail_msg: "{{ item.msg }}"
      loop_control:
        label: "{{ item.msg }}"
      loop:
        - check: device_roles is defined
          msg: "Assert that the host has the device_roles field defined"

    # Prepare
    - name: Manage guest
      include_tasks: "tasks/manage_guest.yml"
      when: 
        - is_virtual
        - technology is defined
        - deploy_guest is defined
        - deploy_guest or deploy_guest == "only"

  tasks:
    - name: Gather Facts
      setup:
      when: '"nixos" not in platforms[0]'

    # Run
    - name: APPLY ROLES
      block:
      - name: Configure hosts
        vars:
          current_roles: "{{ [include_role] if include_role is defined else device_roles | map('regex_replace', '^_', '') | list }}"
        include_role:
          name: "{{ current_role }}"
        loop: "{{ current_roles }}"
        loop_control:
          loop_var: current_role

      - name: STOP STAGED GUEST
        include_tasks: "tasks/manage_guest.yml"
        vars:
          stop_guest: true
        when: 
          - is_virtual
          - technology is defined
          - deploy_guest is defined
          - deploy_guest or deploy_guest == "only"
          - status.value == "staged"

      rescue:
      - debug:
          msg: here comes the rescue task

      - name: Restore guest
        include_tasks: "tasks/restore_guest.yml"
        when:
          - is_virtual
          - technology is defined
          - deploy_guest == "backup" or (upgrade and deploy_guest)
          - not prohibit_restore

      - name: AUTOUP LOCK
        when: upgrade
        block:
        - name: Locking instance for future automated upgrades
          shell:
            cmd: /usr/local/bin/autoup lock Last system upgrade failed
          register: lock_autoup_raw
        
        - debug:
            var: lock_autoup_raw.stdout_lines

        - fail:
            msg: "Playbook failed, system is locked from upgrades"
