---
- name: Update APT package cache
  hosts: "{{ target | default('all') }}"
  gather_facts: true
  serial: "{{ serial | default(false) | bool }}"
  ignore_unreachable: true

  tasks:
    - name: Run apt update
      apt:
        update_cache: yes
      when: 
        - ansible_pkg_mgr is defined
        - ansible_pkg_mgr == "apt"
