---
- name: Update APT package cache
  hosts: "{{ target | default('all') }}"
  gather_facts: true
  serial: "{{ serial | default(false) | bool }}"
  ignore_unreachable: true

  tasks:
    - include_role:
        name: "debian"
        tasks_from: update
      when:
        - ansible_pkg_mgr == "apt"
