---
debian_global_packages:
  # cpu / mem
  - htop

timezone: Europe/Berlin

install_prometheus_node_exporter: true

shell_color: "{% if is_virtual and 'qemu-server' == custom_fields.technology %}red{% elif 'is_virtual' in group_names and 'lxc' == custom_fields.technology %}blue{% elif '_pve_node' in group_names %}yellow{% else %}green{% endif %}"
# vm -> red, lxc -> blue, pve_node -> yellow, else -> green

color_codes: # For shell
  pink:
    tilde: red
    prompt: 31
  green:
    tilde: red
    prompt: 32
  yellow:
    tilde: red
    prompt: 33
  purple:
    tilde: red
    prompt: 34
  red:
    tilde: blue
    prompt: 35
  blue:
    tilde: red
    prompt: 36
  orange:
    tilde: red
    prompt: 37
