---
- name: "Set ansible_local script"
  template:
    src: etc_ansible_facts.d_role_name.fact.j2  # Path to your Python script template
    dest: /etc/ansible/facts.d/{{ role_name }}.fact
    mode: '0700'  # Set the executable permission on the script

- name: "Set ansible_local script wireguard_peers"
  template:
    src: etc_ansible_facts.d_wireguard_peers.fact.j2  # Path to your Python script template
    dest: /etc/ansible/facts.d/{{ role_name }}_peers.fact
    mode: '0700'  # Set the executable permission on the script

- name: Gather ansible_local facts
  setup:
    filter: ansible_local