---
- name: Install necessary packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - wireguard
    - iptables

- name: Enable persistant ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_set: yes
    reload: yes

- name: Adjust permissions of /etc/wireguard
  file:
    path: /etc/wireguard
    owner: root
    group: root
    mode: '700'

- name: Ensure /etc/wireguard/peer-keys directory exists (local facts)
  ansible.builtin.file:
    path: /etc/wireguard/peer-keys
    state: directory
