---
- name: "Role {{ role_name }}"
  vars:
    proxy_routes_: "{{ local_context_data[0]['proxy_routes'] | default(proxy_routes) }}"  
  when:
    - only_role is undefined or only_role == role_name
  block:

  # Assertions
  # - name: "Preventive assertions of role {{ role_name }}"
  #   assert:
  #     that:
  #       - "{{ item.check }}"
  #     fail_msg: "{{ item.msg }}"
  #   loop_control:
  #     label: "{{ item.msg }}"
  #   loop:
  #     - { check: "{{ ansible_python_version is version('3.8', '>=') }}", msg: "Ansible Python version must be above 3.8" }

  # Scripts

  # Tasks
  - import_tasks: install.yml
    when:
      - not quick
  
  - import_tasks: ansible_local.yml
    when:
      - not quick

  - nb_ipam_info:
      api_endpoint: "{{ NB_API_ENDPOINT  }}"
      token: "{{ NB_API_RO_TOKEN }}"
      validate_certs: "{{ NB_VALIDATE_CERTS  }}"
    register: ipam_info
    run_once: true

  - vars:
      wireguard_interfaces: "{{ ipam_info.instances[inventory_hostname].keys() | select('match', '^wg') | list }}"
    import_tasks: configure.yml

  - import_tasks: proxy_traffic.yml
    when:
      - proxy_routes_ is defined

  # Tests
