---
- name: Install nginx for routing
  apt:
    pkg: "{{ item }}"
    state: present
  loop:
    - nginx-core

- debug:
    var: routes_

- name: Place config
  template:
    src: etc_nginx_nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  register: nginx_config

- name: Validate nginx config
  shell:
    cmd: /usr/sbin/nginx -t
  register: validate_nginx_config
  failed_when: false
  changed_when: false

- name: Fail if nginx config is invalid
  fail:
    msg: "{{ validate_nginx_config.stderr_lines }}"
  when: validate_nginx_config.rc != 0

- name: Restart Nginx service
  systemd:
    name: nginx
    state: restarted
  when: 
    - nginx_config.changed