---
- name: "Set ansible_local script"
  template:
    src: etc_ansible_facts.d_pihole.fact.j2  # Path to your Python script template
    dest: /etc/ansible/facts.d/pihole.fact
    mode: '0700'  # Set the executable permission on the script
  register: set_ansible_local
  
- name: Gather ansible_local facts from cluster leader
  delegate_to: "{{ cluster_leader }}"
  ignore_unreachable: true
  setup:
    filter: ansible_local
  register: cluster_leader_ansible_local
  when: 
    - cluster_leader is defined

- name: Gather ansible_local facts
  setup:
    filter: ansible_local
  when: 
    - set_ansible_local.changed
    - ((cluster_leader_ansible_local.unreachable is defined 
      and cluster_leader_ansible_local.unreachable) or 
      cluster_leader is not defined)