---
- name: "Role pihole"
  vars:
    # 1. instance defined
    # 2. cluster defined
    # 3. role defined
    pihole_block_lists_: "{{ local_context_data[0].pihole_block_lists | default(hostvars[cluster_leader].local_context_data[0].pihole_block_lists | default(pihole_block_lists)) }}"
    pihole_whitelisted_domains_: "{{ local_context_data[0].pihole_whitelisted_domains | default(hostvars[cluster_leader].local_context_data[0].pihole_whitelisted_domains | default(pihole_whitelisted_domains)) }}"
  when:
    - only_role is undefined or only_role == "pihole"
  block:
  - name: Assert that there is only one cluster_leader
    assert:
      that: 
        - cluster_leaders | length <= 1
  - name: Tasks outside configure_dns_job
    when:
      - not configure_dns_job
    block:
    - include_tasks: ansible_local.yml

    - include_tasks: install.yml

    - include_tasks: upgrade.yml
      when:
        - upgrade

    - include_tasks: addlists.yml

    - include_tasks: tests.yml

    - include_tasks: prometheus_exporter.yml

  - include_tasks: local_dns.yml

  - run_once: true
    debug:
      msg: "To change the pihole webpassword, run `pihole admin password`"

