---
- name: "Role pihole"
  vars:
    foo: bar
  when:
    - only_role is undefined or only_role == "pihole"
  block:
  - name: Assert that there is only one cluster_leader
    assert:
      that: 
        - cluster_leaders | length <= 1
  - name: Tasks outside configure_dns_job
    when:
      - not configure_dns_job
    block:
    - incude_tasks: ansible_local.yml

    - incude_tasks: install.yml

    - incude_tasks: upgrade.yml
      when:
        - upgrade

    - incude_tasks: tests.yml

    - incude_tasks: prometheus_exporter.yml

  - incude_tasks: local_dns.yml

  - run_once: true
    debug:
      msg: "To change the pihole webpassword, run `pihole admin password`"

# TODO: Write local dns records
