---
- name: Assert that pihole is up and running
  block:
  - name: Check if pihole-FTL.service is running
    ansible.builtin.systemd:
      name: "pihole-FTL.service"
    register: pihole_service_check
    failed_when: pihole_service_check.status.ActiveState != "active"

  - name: Resolve pi-hole.net to ensure pihole is working properly
    shell:
      executable: /bin/bash
      cmd: |
        dig pi-hole.net @127.0.0.1
    register: pihole_test_resolution
    changed_when: false
    failed_when: pihole_test_resolution.rc != 0

  - name: Check if webinterface is available
    shell:
      executable: /bin/bash
      cmd: |
        curl --fail http://localhost/admin
    register: pihole_test_webui
    changed_when: false
    failed_when: pihole_test_webui.rc != 0
