---
- name: Upgrade pihole
  shell:
    executable: /bin/bash
    cmd: |
      /usr/local/bin/pihole updatePihole 2>&1
  register: pihole_update
  when:
    - upgrade

- debug:
    var: pihole_update.stdout_lines
  when:
    - upgrade