---
- name: "Provide netbox secret key"
  delegate_to: "{{ delegate_to_guest_pve_instance }}"
  shell:
    executable: /bin/bash
    cmd: |
      pct exec {{ vmid }} sh <<-EOT
      source /etc/set-environment

      if [ ! -f /var/lib/netbox/secret-key-file ]; then
        mkdir -p /var/lib/netbox/
        nix-shell \
          --packages openssl \
          --command 'openssl rand -hex 50 > /var/lib/netbox/secret-key-file'
        exit 1
      fi

      exit 0
      EOT
  register: create_secret_key
  failed_when: create_secret_key.rc > 1
  changed_when: create_secret_key.rc == 1
