---
- name: "Set ansible_local script"
  template:
    src: "etc_ansible_facts.d_role_name.fact.j2"
    dest: "/etc/ansible/facts.d/{{ role_name }}.fact"
    mode: '0700'
    force: false

- vars:
    INTERRUPT:
      - "NetBox API-Token not set in /etc/ansible/facts.d/{{ role_name }}.fact"
      - "If you didn't create a superuser yet, please create one by running"
      - "`netbox-manage createsuperuser`"
      - "from the containers command line and fill in the token afterwards"
  debug:
    var: INTERRUPT
  failed_when: true
